version: "3.7"
services:
  health-core:
    ports:
      - "8085:8085"
    build: ./
    image: health-core    
    container_name: health-core
    networks:
      network:
        aliases: 
          - health-core
    restart: "always"
    environment:
      - HEALTHCORE_JDBC_PASSWORD=health-core
      - HEALTHCORE_JDBC_USER=health-core
      - HEALTHCORE_JDBC_URL=jdbc:postgresql://postgres-db:5432/healthcore
      - TZ=America/Asuncion
      - LIST_CORS=""
      - LIST_HEADERS=""
      - ALLOW_CORS=false
      - FHIR_SERVER_URL=http://localhost:8088/ptifhir/fhir/
      - AUTH_SERVER_URL=https://localhost:8080/auth/realms/iHub
      - CLIENT_ID=internal-services
      - CLIENT_CREDENTIALS_SECRET=
    depends_on: 
      - postgres_db
  postgres_db:
    image: postgres:11
    container_name: postgres-db
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_DB=healthcore
      - POSTGRES_USER=health-core
      - POSTGRES_PASSWORD=health-core
    volumes:
      - postgres-healthcore:/var/lib/postgresql/data
      - ./health-core-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      network:
        aliases: 
          - postgres-db
    restart: always

networks:
  network:

volumes:
    postgres-healthcore:
